### ISSUE TITLE
CDTV RGB2HDMI v2 (SOIC) - Joystick Fire, and rear Up & Down not working.

### ISSUE THREAD

**Issue by Korinel** [solarmon/RGBtoHDMI-CDTV-v2#3]
I have the CDTV RGB2HDMI v2 (SOIC) and just installed it. The issue is that the Down and Up buttons on the rear do not function (Select is fine) and the fire button on joystick port does not work either. Everything else works fine. Using CDTV Remote and a Brickette joystick cable the button works fine. I have tried with four joysticks, all the same. Fire button 2 and 3 work fine on joystick just not Fire button one. Defective card or installation issue? Anything connected with these three buttons? Any help with diagnoses would be fab!

**Comment by solarmon** [comment]
Hi,

I'm sorry to hear that you have issues with your RGBtoHDMI board.

Please can you contact me on the channel you purchased it from.

**Comment by Korinel** [comment]
All fixed, thanks!
